# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 973a447b45c010d893911fbf1a98a1bd50d5df06cb1268e674eefc9034a89af4d0fc3ba650536901a8d7731e2afbc0aeefae75e8ce1f30e3698663bc5aeeb152

test:
  secret_key_base: b37131484b68953f09920c66705294e5a48ad0fe6042f08991a21d08e188af27ebe4b219d016a6b1543c2cacc986c9954959e71a0f55e84be4e9595099fe4f1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
